package io.github.dbmldiagram.core.ddl

import io.github.dbmldiagram.core.model.DbmlCardinality
import io.github.dbmldiagram.core.model.DbmlColumn
import io.github.dbmldiagram.core.model.DbmlSchema
import io.github.dbmldiagram.core.model.DbmlTable

/** Generates MySQL 8 compatible DDL from the supported DBML model. */
class MySqlDdlGenerator : DdlGenerator {
    override fun generate(schema: DbmlSchema): String = buildString {
        appendLine("-- Generated by DBML Diagram.")
        appendLine("-- Dialect: MySQL 8.")

        schema.tables.mapNotNull { it.schema }.distinct().forEach { schemaName ->
            appendLine()
            appendLine("CREATE SCHEMA IF NOT EXISTS ${quote(schemaName)};")
        }

        schema.tables.forEach { table ->
            appendLine()
            appendLine("CREATE TABLE ${qualified(table)} (")
            val definitions = mutableListOf<String>()
            val primaryKey = primaryKeyColumns(table)
            table.columns.forEach { column ->
                val type = sqlType(column, schema)
                val parts = mutableListOf(quote(column.name), type)
                val autoIncrement = column.increment && isIntegerType(type)
                if (!column.nullable || column.name in primaryKey) parts += "NOT NULL"
                if (!autoIncrement) column.defaultValue?.let { parts += "DEFAULT ${mysqlDefault(it)}" }
                if (autoIncrement) parts += "AUTO_INCREMENT"
                column.note?.let { parts += "COMMENT ${sqlString(it)}" }
                definitions += "    ${parts.joinToString(" ")}"
            }
            if (primaryKey.isNotEmpty()) {
                definitions += "    CONSTRAINT ${quote(name("pk", table.name, primaryKey))} PRIMARY KEY (${columns(primaryKey)})"
            }
            table.columns.filter { it.unique && it.name !in primaryKey }.forEach { column ->
                definitions += "    CONSTRAINT ${quote(name("uq", table.name, listOf(column.name)))} UNIQUE (${quote(column.name)})"
            }
            appendLine(definitions.joinToString(",\n"))
            append(")")
            table.note?.let { append(" COMMENT=${sqlString(it)}") }
            appendLine(";")
        }

        schema.tables.forEach { table ->
            table.indexes.filterNot { it.primaryKey }.forEach { index ->
                appendLine()
                val prefix = if (index.unique) "uq" else "ix"
                val indexName = index.name ?: name(prefix, table.name, index.columns)
                val unique = if (index.unique) "UNIQUE " else ""
                appendLine("CREATE ${unique}INDEX ${quote(indexName)} ON ${qualified(table)} (${columns(index.columns)});")
            }
        }

        schema.references.forEach { reference ->
            val foreignKey = reference.foreignKeyEndpoint()
            val referenced = reference.referencedEndpoint()
            if (foreignKey == null || referenced == null) {
                appendLine()
                appendLine("-- Many-to-many relation ${display(reference.from)} <> ${display(reference.to)} requires an explicit junction table.")
                return@forEach
            }
            val sourceTable = resolveTable(schema, foreignKey)
            val targetTable = resolveTable(schema, referenced)
            val sourceColumn = sourceTable?.columns?.firstOrNull { it.name.equals(foreignKey.column, true) }
            val targetColumn = targetTable?.columns?.firstOrNull { it.name.equals(referenced.column, true) }
            if (sourceTable == null || targetTable == null || sourceColumn == null || targetColumn == null) {
                appendLine()
                appendLine("-- Skipped unresolved reference ${display(reference.from)} -> ${display(reference.to)}.")
                return@forEach
            }

            appendLine()
            if (reference.onDelete?.let(::normalizedAction) == "SET DEFAULT") {
                appendLine("-- MySQL does not support ON DELETE SET DEFAULT; NO ACTION is used instead.")
            }
            if (reference.onUpdate?.let(::normalizedAction) == "SET DEFAULT") {
                appendLine("-- MySQL does not support ON UPDATE SET DEFAULT; NO ACTION is used instead.")
            }
            val constraintName = reference.name ?: name(
                "fk",
                sourceTable.name,
                listOf(sourceColumn.name, targetTable.name, targetColumn.name),
            )
            append("ALTER TABLE ${qualified(sourceTable)} ADD CONSTRAINT ${quote(constraintName)} ")
            append("FOREIGN KEY (${quote(sourceColumn.name)}) REFERENCES ${qualified(targetTable)} (${quote(targetColumn.name)})")
            reference.onDelete?.let { append(" ON DELETE ${mysqlAction(it)}") }
            reference.onUpdate?.let { append(" ON UPDATE ${mysqlAction(it)}") }
            appendLine(";")

            if (reference.cardinality == DbmlCardinality.ONE_TO_ONE && !isUnique(sourceTable, sourceColumn.name)) {
                appendLine(
                    "ALTER TABLE ${qualified(sourceTable)} ADD CONSTRAINT " +
                        "${quote(name("uq", sourceTable.name, listOf(sourceColumn.name)))} UNIQUE (${quote(sourceColumn.name)});",
                )
            }
        }
    }

    private fun sqlType(column: DbmlColumn, schema: DbmlSchema): String {
        val trimmed = column.type.trim()
        schema.enums.firstOrNull { it.name.equals(trimmed, true) }?.let { enum ->
            return "ENUM(${enum.values.joinToString(", ") { sqlString(it) }})"
        }
        Regex("(?i)^varchar\\s*\\((.+)\\)$").matchEntire(trimmed)?.let { return "VARCHAR(${it.groupValues[1]})" }
        Regex("(?i)^char\\s*\\((.+)\\)$").matchEntire(trimmed)?.let { return "CHAR(${it.groupValues[1]})" }
        Regex("(?i)^(decimal|numeric)\\s*\\((.+)\\)$").matchEntire(trimmed)?.let { return "DECIMAL(${it.groupValues[2]})" }
        return when (trimmed.lowercase()) {
            "uuid" -> "CHAR(36)"
            "int", "integer", "serial" -> "INT"
            "smallint", "smallserial" -> "SMALLINT"
            "bigint", "bigserial" -> "BIGINT"
            "double precision", "float8" -> "DOUBLE"
            "real", "float4" -> "FLOAT"
            "decimal", "numeric" -> "DECIMAL"
            "timestamptz", "timestamp with time zone" -> "TIMESTAMP"
            "timestamp" -> "TIMESTAMP"
            "datetime" -> "DATETIME"
            "date" -> "DATE"
            "time" -> "TIME"
            "bool" -> "BOOLEAN"
            "jsonb" -> "JSON"
            "text[]" -> "JSON"
            "text" -> "TEXT"
            "blob", "bytea" -> "BLOB"
            else -> trimmed
        }
    }

    private fun mysqlDefault(value: String): String = when (value.trim().lowercase()) {
        "true" -> "TRUE"
        "false" -> "FALSE"
        else -> value
    }

    private fun mysqlAction(value: String): String = when (val action = normalizedAction(value)) {
        "SET DEFAULT" -> "NO ACTION"
        else -> action
    }

    private fun isIntegerType(type: String) = type.uppercase() in setOf("TINYINT", "SMALLINT", "MEDIUMINT", "INT", "INTEGER", "BIGINT")

    private fun qualified(table: DbmlTable): String =
        table.schema?.let { "${quote(it)}.${quote(table.name)}" } ?: quote(table.name)

    private fun columns(values: List<String>) = values.joinToString(", ") { quote(it) }

    private fun quote(identifier: String) = "`${identifier.replace("`", "``")}`"

    private fun name(prefix: String, table: String, parts: List<String>) = safeName(prefix, table, parts, 64)
}
