package io.github.dbmldiagram.core.ddl

import io.github.dbmldiagram.core.model.DbmlCardinality
import io.github.dbmldiagram.core.model.DbmlColumn
import io.github.dbmldiagram.core.model.DbmlEnum
import io.github.dbmldiagram.core.model.DbmlSchema
import io.github.dbmldiagram.core.model.DbmlTable

/** Generates Oracle Database compatible DDL from the supported DBML model. */
class OracleDdlGenerator : DdlGenerator {
    override fun generate(schema: DbmlSchema): String = buildString {
        appendLine("-- Generated by DBML Diagram.")
        appendLine("-- Dialect: Oracle Database 12c+.")
        if (schema.tables.any { it.schema != null }) {
            appendLine("-- Schema-qualified objects assume that the corresponding Oracle users/schemas already exist.")
        }

        schema.tables.forEach { table ->
            appendLine()
            appendLine("CREATE TABLE ${qualified(table)} (")
            val definitions = mutableListOf<String>()
            val primaryKey = primaryKeyColumns(table)
            table.columns.forEach { column ->
                val enum = enumFor(column, schema)
                val type = sqlType(column.type, enum)
                val parts = mutableListOf(quote(column.name), type)
                val identity = column.increment && isNumericType(type)
                if (identity) parts += "GENERATED BY DEFAULT AS IDENTITY"
                if (!identity) column.defaultValue?.let { parts += "DEFAULT ${oracleDefault(it)}" }
                if (!column.nullable || column.name in primaryKey) parts += "NOT NULL"
                definitions += "    ${parts.joinToString(" ")}"
                if (enum != null) {
                    definitions += "    CONSTRAINT ${quote(name("ck", table.name, listOf(column.name)))} CHECK (${quote(column.name)} IN (${enum.values.joinToString(", ") { sqlString(it) }}))"
                }
                if (column.type.trim().equals("bool", true) || column.type.trim().equals("boolean", true)) {
                    definitions += "    CONSTRAINT ${quote(name("ck", table.name, listOf(column.name, "bool")))} CHECK (${quote(column.name)} IN (0, 1))"
                }
            }
            if (primaryKey.isNotEmpty()) {
                definitions += "    CONSTRAINT ${quote(name("pk", table.name, primaryKey))} PRIMARY KEY (${columns(primaryKey)})"
            }
            table.columns.filter { it.unique && it.name !in primaryKey }.forEach { column ->
                definitions += "    CONSTRAINT ${quote(name("uq", table.name, listOf(column.name)))} UNIQUE (${quote(column.name)})"
            }
            appendLine(definitions.joinToString(",\n"))
            appendLine(");")
        }

        schema.tables.forEach { table ->
            table.indexes.filterNot { it.primaryKey }.forEach { index ->
                appendLine()
                val prefix = if (index.unique) "uq" else "ix"
                val indexName = index.name ?: name(prefix, table.name, index.columns)
                val unique = if (index.unique) "UNIQUE " else ""
                appendLine("CREATE ${unique}INDEX ${quote(indexName)} ON ${qualified(table)} (${columns(index.columns)});")
            }
        }

        schema.references.forEach { reference ->
            val foreignKey = reference.foreignKeyEndpoint()
            val referenced = reference.referencedEndpoint()
            if (foreignKey == null || referenced == null) {
                appendLine()
                appendLine("-- Many-to-many relation ${display(reference.from)} <> ${display(reference.to)} requires an explicit junction table.")
                return@forEach
            }
            val sourceTable = resolveTable(schema, foreignKey)
            val targetTable = resolveTable(schema, referenced)
            val sourceColumn = sourceTable?.columns?.firstOrNull { it.name.equals(foreignKey.column, true) }
            val targetColumn = targetTable?.columns?.firstOrNull { it.name.equals(referenced.column, true) }
            if (sourceTable == null || targetTable == null || sourceColumn == null || targetColumn == null) {
                appendLine()
                appendLine("-- Skipped unresolved reference ${display(reference.from)} -> ${display(reference.to)}.")
                return@forEach
            }

            appendLine()
            reference.onUpdate?.let { appendLine("-- Oracle does not support ON UPDATE $it; action omitted for this constraint.") }
            val deleteAction = reference.onDelete?.let(::oracleDeleteAction)
            if (reference.onDelete != null && deleteAction == null && normalizedAction(reference.onDelete) !in setOf("NO ACTION", "RESTRICT")) {
                appendLine("-- Oracle does not support ON DELETE ${reference.onDelete}; action omitted for this constraint.")
            }
            val constraintName = reference.name ?: name(
                "fk",
                sourceTable.name,
                listOf(sourceColumn.name, targetTable.name, targetColumn.name),
            )
            append("ALTER TABLE ${qualified(sourceTable)} ADD CONSTRAINT ${quote(constraintName)} ")
            append("FOREIGN KEY (${quote(sourceColumn.name)}) REFERENCES ${qualified(targetTable)} (${quote(targetColumn.name)})")
            deleteAction?.let { append(" ON DELETE $it") }
            appendLine(";")

            if (reference.cardinality == DbmlCardinality.ONE_TO_ONE && !isUnique(sourceTable, sourceColumn.name)) {
                appendLine(
                    "ALTER TABLE ${qualified(sourceTable)} ADD CONSTRAINT " +
                        "${quote(name("uq", sourceTable.name, listOf(sourceColumn.name)))} UNIQUE (${quote(sourceColumn.name)});",
                )
            }
        }

        schema.tables.forEach { table ->
            table.note?.let {
                appendLine()
                appendLine("COMMENT ON TABLE ${qualified(table)} IS ${sqlString(it)};")
            }
            table.columns.forEach { column ->
                column.note?.let {
                    appendLine("COMMENT ON COLUMN ${qualified(table)}.${quote(column.name)} IS ${sqlString(it)};")
                }
            }
        }
    }

    private fun enumFor(column: DbmlColumn, schema: DbmlSchema): DbmlEnum? =
        schema.enums.firstOrNull { it.name.equals(column.type.trim(), true) }

    private fun sqlType(type: String, enum: DbmlEnum?): String {
        if (enum != null) return "VARCHAR2(${enum.values.maxOfOrNull(String::length)?.coerceAtLeast(1) ?: 1})"
        val trimmed = type.trim()
        val varchar = Regex("(?i)^varchar(?:2)?\\s*\\((.+)\\)$").matchEntire(trimmed)
        if (varchar != null) return "VARCHAR2(${varchar.groupValues[1]})"
        val char = Regex("(?i)^char\\s*\\((.+)\\)$").matchEntire(trimmed)
        if (char != null) return "CHAR(${char.groupValues[1]})"
        return when (trimmed.lowercase()) {
            "uuid" -> "VARCHAR2(36)"
            "smallint" -> "NUMBER(5)"
            "int", "integer", "serial" -> "NUMBER(10)"
            "bigint", "bigserial" -> "NUMBER(19)"
            "decimal", "numeric" -> "NUMBER"
            "double", "double precision", "float8" -> "BINARY_DOUBLE"
            "real", "float", "float4" -> "BINARY_FLOAT"
            "datetime", "timestamp" -> "TIMESTAMP"
            "timestamptz", "timestamp with time zone" -> "TIMESTAMP WITH TIME ZONE"
            "bool", "boolean" -> "NUMBER(1)"
            "text" -> "CLOB"
            "bytea", "blob" -> "BLOB"
            "json", "jsonb" -> "CLOB"
            else -> trimmed.uppercase()
        }
    }

    private fun oracleDefault(value: String): String = when (value.trim().lowercase()) {
        "true" -> "1"
        "false" -> "0"
        "now()" -> "CURRENT_TIMESTAMP"
        else -> value
    }

    private fun oracleDeleteAction(value: String): String? = when (normalizedAction(value)) {
        "CASCADE" -> "CASCADE"
        "SET NULL" -> "SET NULL"
        else -> null
    }

    private fun isNumericType(type: String) =
        type.startsWith("NUMBER", true) || type.equals("BINARY_FLOAT", true) || type.equals("BINARY_DOUBLE", true)

    private fun qualified(table: DbmlTable): String =
        table.schema?.let { "${quote(it)}.${quote(table.name)}" } ?: quote(table.name)

    private fun columns(values: List<String>) = values.joinToString(", ") { quote(it) }

    private fun quote(identifier: String) = "\"${identifier.replace("\"", "\"\"")}\""

    private fun name(prefix: String, table: String, parts: List<String>) = safeName(prefix, table, parts, 30)
}
