package io.github.dbmldiagram.core.ddl

import io.github.dbmldiagram.core.model.DbmlCardinality
import io.github.dbmldiagram.core.model.DbmlColumnRef
import io.github.dbmldiagram.core.model.DbmlReference
import io.github.dbmldiagram.core.model.DbmlSchema
import io.github.dbmldiagram.core.model.DbmlTable

/** Generates executable PostgreSQL DDL from the supported DBML model. */
class PostgreSqlDdlGenerator : DdlGenerator {
    override fun generate(schema: DbmlSchema): String = buildString {
        appendLine("-- Generated by DBML Diagram.")
        appendLine("-- Dialect: PostgreSQL.")
        appendLine("BEGIN;")

        schema.tables.mapNotNull { it.schema }.distinct().forEach { schemaName ->
            appendLine()
            appendLine("CREATE SCHEMA IF NOT EXISTS ${quote(schemaName)};")
        }

        schema.enums.forEach { enum ->
            appendLine()
            val values = enum.values.joinToString(", ") { sqlString(it) }
            appendLine("CREATE TYPE ${quote(enum.name)} AS ENUM ($values);")
        }

        schema.tables.forEach { table ->
            appendLine()
            appendLine("CREATE TABLE ${qualified(table)} (")
            val definitions = mutableListOf<String>()
            val primaryKey = primaryKeyColumns(table)
            table.columns.forEach { column ->
                val type = sqlType(column.type, schema)
                val parts = mutableListOf(quote(column.name), type)
                if (column.increment && type.lowercase() in setOf("smallint", "integer", "bigint")) {
                    parts += "GENERATED BY DEFAULT AS IDENTITY"
                }
                if (!column.nullable || column.name in primaryKey) parts += "NOT NULL"
                column.defaultValue?.let { parts += "DEFAULT $it" }
                definitions += "    ${parts.joinToString(" ")}"
            }
            if (primaryKey.isNotEmpty()) {
                definitions += "    CONSTRAINT ${quote(name("pk", table.name, primaryKey))} PRIMARY KEY (${columns(primaryKey)})"
            }
            table.columns.filter { it.unique && it.name !in primaryKey }.forEach { column ->
                definitions += "    CONSTRAINT ${quote(name("uq", table.name, listOf(column.name)))} UNIQUE (${quote(column.name)})"
            }
            appendLine(definitions.joinToString(",\n"))
            appendLine(");")
        }

        schema.tables.forEach { table ->
            table.indexes.filterNot { it.primaryKey }.forEach { index ->
                appendLine()
                val prefix = if (index.unique) "uq" else "ix"
                val indexName = index.name ?: name(prefix, table.name, index.columns)
                val unique = if (index.unique) "UNIQUE " else ""
                appendLine("CREATE ${unique}INDEX ${quote(indexName)} ON ${qualified(table)} (${columns(index.columns)});")
            }
        }

        schema.references.forEach { reference ->
            val endpoints = foreignKeyEndpoints(reference)
            if (endpoints == null) {
                appendLine()
                appendLine("-- Many-to-many relation ${display(reference.from)} <> ${display(reference.to)} requires an explicit junction table.")
                return@forEach
            }
            val sourceTable = resolveTable(schema, endpoints.first)
            val targetTable = resolveTable(schema, endpoints.second)
            if (sourceTable == null || targetTable == null) {
                appendLine()
                appendLine("-- Skipped unresolved reference ${display(reference.from)} -> ${display(reference.to)}.")
                return@forEach
            }
            val sourceColumn = sourceTable.columns.firstOrNull { it.name.equals(endpoints.first.column, true) }
            val targetColumn = targetTable.columns.firstOrNull { it.name.equals(endpoints.second.column, true) }
            if (sourceColumn == null || targetColumn == null) {
                appendLine()
                appendLine("-- Skipped unresolved reference ${display(reference.from)} -> ${display(reference.to)}.")
                return@forEach
            }

            appendLine()
            val constraintName = reference.name ?: name(
                "fk",
                sourceTable.name,
                listOf(sourceColumn.name, targetTable.name, targetColumn.name),
            )
            append("ALTER TABLE ${qualified(sourceTable)} ADD CONSTRAINT ${quote(constraintName)} ")
            append("FOREIGN KEY (${quote(sourceColumn.name)}) REFERENCES ${qualified(targetTable)} (${quote(targetColumn.name)})")
            reference.onDelete?.let { append(" ON DELETE ${referentialAction(it)}") }
            reference.onUpdate?.let { append(" ON UPDATE ${referentialAction(it)}") }
            appendLine(";")

            if (reference.cardinality == DbmlCardinality.ONE_TO_ONE && !isUnique(sourceTable, sourceColumn.name)) {
                appendLine(
                    "ALTER TABLE ${qualified(sourceTable)} ADD CONSTRAINT " +
                        "${quote(name("uq", sourceTable.name, listOf(sourceColumn.name)))} UNIQUE (${quote(sourceColumn.name)});",
                )
            }
        }

        schema.tables.forEach { table ->
            table.note?.let {
                appendLine()
                appendLine("COMMENT ON TABLE ${qualified(table)} IS ${sqlString(it)};")
            }
            table.columns.forEach { column ->
                column.note?.let {
                    appendLine("COMMENT ON COLUMN ${qualified(table)}.${quote(column.name)} IS ${sqlString(it)};")
                }
            }
        }

        appendLine()
        appendLine("COMMIT;")
    }

    private fun primaryKeyColumns(table: DbmlTable): List<String> =
        table.indexes.firstOrNull { it.primaryKey }?.columns
            ?: table.columns.filter { it.primaryKey }.map { it.name }

    private fun isUnique(table: DbmlTable, column: String): Boolean =
        column in primaryKeyColumns(table) ||
            table.columns.any { it.name.equals(column, true) && it.unique } ||
            table.indexes.any { it.unique && it.columns.size == 1 && it.columns.single().equals(column, true) }

    private fun foreignKeyEndpoints(reference: DbmlReference): Pair<DbmlColumnRef, DbmlColumnRef>? = when (reference.cardinality) {
        DbmlCardinality.MANY_TO_ONE -> reference.from to reference.to
        DbmlCardinality.ONE_TO_MANY -> reference.to to reference.from
        DbmlCardinality.ONE_TO_ONE -> if (reference.inline) {
            reference.from to reference.to
        } else {
            reference.to to reference.from
        }
        DbmlCardinality.MANY_TO_MANY -> null
    }

    private fun resolveTable(schema: DbmlSchema, reference: DbmlColumnRef): DbmlTable? =
        schema.tables.firstOrNull {
            it.qualifiedName.equals(reference.tableName, true) ||
                (reference.schema == null && it.alias?.equals(reference.table, true) == true)
        }

    private fun sqlType(type: String, schema: DbmlSchema): String {
        val trimmed = type.trim()
        schema.enums.firstOrNull { it.name.equals(trimmed, true) }?.let { return quote(it.name) }
        return when (trimmed.lowercase()) {
            "int" -> "integer"
            "double", "float8" -> "double precision"
            "float", "float4" -> "real"
            "datetime" -> "timestamp"
            "bool" -> "boolean"
            else -> trimmed
        }
    }

    private fun referentialAction(value: String): String = when (value.trim().replace('_', ' ').lowercase()) {
        "cascade" -> "CASCADE"
        "restrict" -> "RESTRICT"
        "set null" -> "SET NULL"
        "set default" -> "SET DEFAULT"
        "no action" -> "NO ACTION"
        else -> value.trim().uppercase()
    }

    private fun qualified(table: DbmlTable): String =
        table.schema?.let { "${quote(it)}.${quote(table.name)}" } ?: quote(table.name)

    private fun columns(values: List<String>) = values.joinToString(", ") { quote(it) }

    private fun quote(identifier: String) = "\"${identifier.replace("\"", "\"\"")}\""

    private fun sqlString(value: String) = "'${value.replace("'", "''")}'"

    private fun name(prefix: String, table: String, parts: List<String>): String {
        val raw = (listOf(prefix, table) + parts).joinToString("_")
            .lowercase()
            .replace(Regex("[^a-z0-9_]+"), "_")
            .trim('_')
        return raw.take(63)
    }

    private fun display(reference: DbmlColumnRef) = "${reference.tableName}.${reference.column}"
}
