package io.github.dbmldiagram.core.ddl

import io.github.dbmldiagram.core.parser.TolerantDbmlParser
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse

class OracleDdlGeneratorTest {
    @Test
    fun `generates Oracle types enum checks identity comments and supported actions`() {
        val result = TolerantDbmlParser().parse(
            """
            Project archive { database_type: 'Oracle' }
            Enum state { NEW
              READY
            }
            Table app.users [note: 'Application users'] {
              id bigint [pk, increment]
              external_id uuid [not null]
              active bool [not null, default: true]
              created_at timestamptz [not null, default: `now()`]
              email varchar(255) [note: 'Login address']
            }
            Table app.documents {
              id bigint [pk, increment]
              user_id bigint [not null]
              state state [not null, default: 'NEW']
            }
            Ref fk_documents_users: app.documents.user_id > app.users.id [delete: cascade, update: no action]
            """.trimIndent(),
        )
        assertFalse(result.hasErrors, result.errors.toString())

        val ddl = OracleDdlGenerator().generate(result.schema!!)

        assertContains(ddl, "-- Dialect: Oracle Database 12c+.")
        assertContains(ddl, "\"id\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL")
        assertContains(ddl, "\"external_id\" VARCHAR2(36) NOT NULL")
        assertContains(ddl, "\"active\" NUMBER(1) DEFAULT 1 NOT NULL")
        assertContains(ddl, "\"created_at\" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL")
        assertContains(ddl, "\"state\" VARCHAR2(5) DEFAULT 'NEW' NOT NULL")
        assertContains(ddl, "CHECK (\"state\" IN ('NEW', 'READY'))")
        assertContains(ddl, "Oracle does not support ON UPDATE no action")
        assertContains(ddl, "FOREIGN KEY (\"user_id\") REFERENCES \"app\".\"users\" (\"id\") ON DELETE CASCADE;")
        assertContains(ddl, "COMMENT ON TABLE \"app\".\"users\" IS 'Application users';")
        assertContains(ddl, "COMMENT ON COLUMN \"app\".\"users\".\"email\" IS 'Login address';")
    }
}
