package io.github.dbmldiagram.core.ddl

import io.github.dbmldiagram.core.parser.TolerantDbmlParser
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse

class PostgreSqlDdlGeneratorTest {
    private val parser = TolerantDbmlParser()
    private val generator = PostgreSqlDdlGenerator()

    @Test
    fun `generates tables keys indexes references actions defaults and comments`() {
        val result = parser.parse(
            """
            Project archive { database_type: 'PostgreSQL' }
            Enum order_status { CREATED
              PAID
            }
            Table auth.users [note: 'Application users'] {
              tenant_id uuid [not null]
              id uuid [not null]
              email varchar(255) [not null, unique, note: 'Login address']
              created_at timestamptz [not null, default: `now()`]
              display_name text [default: 'guest']
              indexes {
                (tenant_id, id) [pk]
                email [name: 'ix_users_email']
              }
            }
            Table sales.orders {
              id bigint [pk, increment]
              user_id uuid [not null]
              status order_status [not null, default: 'CREATED']
            }
            Ref fk_orders_users: sales.orders.user_id > auth.users.id [delete: cascade, update: no action]
            """.trimIndent(),
        )
        assertFalse(result.hasErrors, result.errors.toString())

        val ddl = generator.generate(result.schema!!)

        assertContains(ddl, "CREATE SCHEMA IF NOT EXISTS \"auth\";")
        assertContains(ddl, "CREATE TYPE \"order_status\" AS ENUM ('CREATED', 'PAID');")
        assertContains(ddl, "CONSTRAINT \"pk_users_tenant_id_id\" PRIMARY KEY (\"tenant_id\", \"id\")")
        assertContains(ddl, "CONSTRAINT \"uq_users_email\" UNIQUE (\"email\")")
        assertContains(ddl, "\"created_at\" timestamptz DEFAULT now() NOT NULL")
        assertContains(ddl, "\"display_name\" text DEFAULT 'guest'")
        assertContains(ddl, "\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL")
        assertContains(ddl, "CREATE INDEX \"ix_users_email\" ON \"auth\".\"users\" (\"email\");")
        assertContains(ddl, "CONSTRAINT \"fk_orders_users\" FOREIGN KEY (\"user_id\") REFERENCES \"auth\".\"users\" (\"id\") ON DELETE CASCADE ON UPDATE NO ACTION;")
        assertContains(ddl, "COMMENT ON TABLE \"auth\".\"users\" IS 'Application users';")
        assertContains(ddl, "COMMENT ON COLUMN \"auth\".\"users\".\"email\" IS 'Login address';")
        assertContains(ddl, "COMMIT;")
    }

    @Test
    fun `reverses one to many reference so foreign key is on many side`() {
        val schema = parser.parse(
            """
            Table users { id uuid [pk] }
            Table orders { user_id uuid [not null] }
            Ref: users.id < orders.user_id
            """.trimIndent(),
        ).schema!!

        val ddl = generator.generate(schema)

        assertContains(ddl, "ALTER TABLE \"orders\"")
        assertContains(ddl, "FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\")")
    }

    @Test
    fun `uses second endpoint as foreign key for short one to one refs`() {
        val schema = parser.parse("""
            Table users { id uuid [pk] }
            Table profiles { user_id uuid [pk] }
            Ref: users.id - profiles.user_id
        """.trimIndent()).schema!!

        val ddl = generator.generate(schema)

        assertContains(ddl, "ALTER TABLE \"profiles\"")
        assertContains(ddl, "FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\")")
    }

    @Test
    fun `uses declaring column as foreign key for inline one to one refs`() {
        val schema = parser.parse("""
            Table users { id uuid [pk] }
            Table profiles { user_id uuid [pk, ref: - users.id] }
        """.trimIndent()).schema!!

        val ddl = generator.generate(schema)

        assertContains(ddl, "ALTER TABLE \"profiles\"")
        assertContains(ddl, "FOREIGN KEY (\"user_id\") REFERENCES \"users\" (\"id\")")
    }
}
